version: '3'

services:

  api:
    container_name: api
    build: api
    depends_on:
      - database
    volumes:
      - ./api:/var/www/api

  client:
    container_name: client
    build: client
    volumes:
      - ./client:/home/node/client
    ports:
      - 80:4200

  nginx:
    container_name: nginx
    image: nginx:1.15
    links:
      - api
    volumes:
      - ./api:/var/www/api
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 81:80

  database:
    container_name: database
    image: mariadb:10.3-jessie
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - 3307:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.7
    links:
      - database:db
    ports:
      - 82:80

volumes:
  api: